### ISSUE TITLE
bustub/test/primer/starter_test.cpp line45 and line75 it's better to use std::move()

### ISSUE THREAD

**Issue by iwanttobepowerful** [cmu-db/bustub#114]
bustub/test/primer/starter_test.cpp line45 and line75 it's better to use std::move()
std::unique_ptr<RowMatrix<int>> sum_ptr = RowMatrixOperations<int>::AddMatrices(move(mat1_ptr), move(mat2_ptr));

**Comment by apavlo** [comment]
@iwanttobepowerful Can you send a PR with the fix?

**Comment by moaz-eldefrawy** [comment]
@apavlo 
I can do that?

**Comment by apavlo** [comment]
@moaz-eldefrawy yes go for it!
