### ISSUE TITLE
can open more test case in gradescope?

### ISSUE THREAD

**Issue by iwanttobepowerful** [cmu-db/bustub#115]
Hi, professor. Can open more test case in gradescope for debug easier? Thanks! @apavlo

**Comment by apavlo** [comment]
I don't understand what you are asking?

**Comment by iwanttobepowerful** [comment]
> I don't understand what you are asking?

sorry. My English is so poor. Can you add more test cases in test files? Thanks.

**Comment by apavlo** [comment]
We encourage students to write their own tests. The ones we provide are fairly comprehensive. We just cannot release the source code for them.
