### ISSUE TITLE
Bad behavior for REPEATABLE_READ in lock_manager_test.cpp

### ISSUE THREAD

**Issue by BanYeung** [cmu-db/bustub#131]
A txn wiith a REPEATABLE_READ isolation level should use the Strong-Strict 2PL, that is, it should release all the locks it holds only when it is committed or aborted.  

For Bustub, a txn with a REPEATABLE_READ isolation level should not call `LockManager::Unlock()` at all, all the unlocking(whatever mode) should be defered to `TransactionManager::Commit()` or `Abort()`.

`BasicTest1()` in lock_manager_test.cpp violates this rule, so the LockManager should set the state of the txn to ABORTED rather than SHRINKING. Put it in another way, there should be no SHRINKING state for a REPEATABLE_READ txn.

Am I correct?

**Comment by apavlo** [comment]
Please post your question on Piazza.
