### ISSUE TITLE
p1, some doubt? Hope for some guide

### ISSUE THREAD

**Issue by FrankSzn** [cmu-db/bustub#132]
In p1, when we delete a page calling BufferPoolManager::DeletePageImpl(page_id_t page_id)？ should we victim the page at the same time, when  the frame exist in the replacer because its pin count is 0。
Or when we find a victim page, we should check whether this frameId is meaningful, but it thinks a higher cost

**Comment by lmwnshn** [comment]
> In exchange for making this available to the public, we ask that you do not make your project implementations public on Github or other source code repositories.

https://15445.courses.cs.cmu.edu/fall2020/faq.html#q5

> WHERE CAN I GO TO DISCUSS THE COURSE MATERIAL OR PROJECTS?

https://15445.courses.cs.cmu.edu/fall2020/faq.html#q6

**Comment by FrankSzn** [comment]
sorry! you can delete the issue to avoid the problem. Thanks for the learning project.
