### ISSUE TITLE
Buffer Pool project test_memory_safety: Timeout Happened during valgrind

### ISSUE THREAD

**Issue by ABE-Mark45** [cmu-db/bustub#133]
I have been tackling the buffer pool project for about 2 days now and passed all tests, except for this test shown below. The thing is I don't allocate anything in the memory other than the boilerplate code provided in the repo, and checked line by line if I'm doing something wrong. I doubted that maybe a deadlock happened, but it is weird as I passed the concurrency test. It is also weird that it gives me a timeout error in a memory safety test, so is it a problem with implementation efficiency?
![image](https://user-images.githubusercontent.com/56171892/106006901-646f4a80-60be-11eb-855f-54466f9fb0d2.png)

**Comment by apavlo** [comment]
https://15445.courses.cs.cmu.edu/fall2020/faq.html#q6

**Comment by rain-sumire** [comment]
🍀

**Comment by iiiuwioajdks** [comment]
maybe your implement is too slow

**Comment by herocbn** [comment]
I met the same issue, did  u get an ans?
