### ISSUE TITLE
all tests error or failed on gradescope

### ISSUE THREAD

**Issue by JunfengZZZZhou** [cmu-db/bustub#139]
Hi, I submitted my code of project2 and got all the tests failed and the build and memory safety test show error.
lilke

test_Replacer_Victim (__main__.TestProject2) (0.0/0.0)
Test Failed: False is not true : Test [LRUReplacerTest.Victim] failed.

test_memory_safety (__main__.TestProject2) (0.0/10.0)
Test Failed: False is not true : Valgrind errored:
valgrind: ./grading_b_plus_tree_checkpoint_1_test: No such file or directory

test_build (__main__.TestProject2) (0.0/0.0)
Test Failed: False is not true : Build errored: 

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BusTub/main found clang-format at /usr/bin/clang-format-8
-- BusTub/main found clang-tidy at /usr/bin/clang-tidy-8
-- BusTub/main found cpplint at /autograder/bustub/build_support/cpplint.py
-- Configuring done
-- Generating done
-- Build files have been written to: /autograder/bustub/build/googletest-download
Scanning dependencies of target googletest
[ 11%] Creating directories for 'googletest'
[ 22%] Performing download step (git clone) for 'googletest'
Cloning into 'googletest-src'...
Already on 'master'
Your branch is up to date with 'origin/master'.
[ 33%] No patch step for 'googletest'
[ 44%] Performing update step for 'googletest'
Current branch master is up to date.
[ 55%] No configure step for 'googletest'
[ 66%] No build step for 'googletest'
[ 77%] No install step for 'googletest'
[ 88%] No test step for 'googletest'
[100%] Completed 'googletest'
[100%] Built target googletest
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- CMAKE_CXX_FLAGS:  -fPIC -Wall -Wextra -Werror -march=native -Wno-unused-parameter -Wno-attributes
-- CMAKE_CXX_FLAGS_DEBUG: -g -O0 -ggdb -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls
-- CMAKE_EXE_LINKER_FLAGS:  -fPIC
-- CMAKE_SHARED_LINKER_FLAGS:  -fPIC
-- BusTub/test found valgrind at /usr/bin/valgrind
-- Configuring done
-- Generating done
-- Build files have been written to: /autograder/bustub/build

Scanning dependencies of target thirdparty_murmur3
Scanning dependencies of target gtest
[  1%] Building CXX object src/CMakeFiles/thirdparty_murmur3.dir/__/third_party/murmur3/MurmurHash3.cpp.o
[  3%] Building CXX object googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  5%] Linking CXX shared library ../lib/libthirdparty_murmur3.so
[  5%] Built target thirdparty_murmur3
Scanning dependencies of target bustub_shared
[  7%] Building CXX object src/CMakeFiles/bustub_shared.dir/buffer/buffer_pool_manager.cpp.o
[ 11%] Building CXX object src/CMakeFiles/bustub_shared.dir/buffer/lru_replacer.cpp.o
[ 11%] Building CXX object src/CMakeFiles/bustub_shared.dir/buffer/clock_replacer.cpp.o
[ 13%] Building CXX object src/CMakeFiles/bustub_shared.dir/catalog/column.cpp.o
[ 15%] Building CXX object src/CMakeFiles/bustub_shared.dir/catalog/schema.cpp.o
[ 17%] Building CXX object src/CMakeFiles/bustub_shared.dir/catalog/table_generator.cpp.o
[ 19%] Building CXX object src/CMakeFiles/bustub_shared.dir/common/config.cpp.o
[ 21%] Building CXX object src/CMakeFiles/bustub_shared.dir/common/util/string_util.cpp.o
[ 21%] Building CXX object src/CMakeFiles/bustub_shared.dir/concurrency/lock_manager.cpp.o
[ 23%] Building CXX object src/CMakeFiles/bustub_shared.dir/concurrency/transaction_manager.cpp.o
[ 25%] Building CXX object src/CMakeFiles/bustub_shared.dir/container/hash/linear_probe_hash_table.cpp.o
[ 27%] Building CXX object src/CMakeFiles/bustub_shared.dir/execution/aggregation_executor.cpp.o
[ 29%] Building CXX object src/CMakeFiles/bustub_shared.dir/execution/executor_factory.cpp.o
[ 31%] Building CXX object src/CMakeFiles/bustub_shared.dir/execution/hash_join_executor.cpp.o
[ 33%] Building CXX object src/CMakeFiles/bustub_shared.dir/execution/insert_executor.cpp.o
[ 37%] Building CXX object src/CMakeFiles/bustub_shared.dir/execution/seq_scan_executor.cpp.o
[ 37%] Linking CXX shared library ../../lib/libgtest.so
[ 37%] Built target gtest
[ 39%] Building CXX object src/CMakeFiles/bustub_shared.dir/recovery/checkpoint_manager.cpp.o
Scanning dependencies of target gmock
[ 41%] Building CXX object googletest-build/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
[ 43%] Building CXX object src/CMakeFiles/bustub_shared.dir/recovery/log_manager.cpp.o
Scanning dependencies of target gtest_main
[ 45%] Building CXX object googletest-build/googletest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[ 45%] Building CXX object src/CMakeFiles/bustub_shared.dir/recovery/log_recovery.cpp.o
[ 47%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/disk/disk_manager.cpp.o
[ 49%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/index/b_plus_tree.cpp.o
[ 50%] Linking CXX shared library ../../lib/libgtest_main.so
[ 52%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/index/b_plus_tree_index.cpp.o
[ 52%] Built target gtest_main
[ 54%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/index/index_iterator.cpp.o
[ 54%] Linking CXX shared library ../../lib/libgmock.so
[ 54%] Built target gmock
[ 56%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/index/linear_probe_hash_table_index.cpp.o
Scanning dependencies of target gmock_main
[ 58%] Building CXX object googletest-build/googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
[ 60%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/page/b_plus_tree_internal_page.cpp.o
[ 62%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/page/b_plus_tree_leaf_page.cpp.o
[ 64%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/page/b_plus_tree_page.cpp.o
[ 64%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/page/hash_table_block_page.cpp.o
[ 66%] Linking CXX shared library ../../lib/libgmock_main.so
[ 68%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/page/hash_table_header_page.cpp.o
[ 70%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/page/header_page.cpp.o
[ 70%] Built target gmock_main
[ 72%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/page/table_page.cpp.o
[ 74%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/table/table_heap.cpp.o
[ 76%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/table/table_iterator.cpp.o
[ 78%] Building CXX object src/CMakeFiles/bustub_shared.dir/storage/table/tuple.cpp.o
[ 80%] Building CXX object src/CMakeFiles/bustub_shared.dir/type/bigint_type.cpp.o
[ 82%] Building CXX object src/CMakeFiles/bustub_shared.dir/type/boolean_type.cpp.o
[ 82%] Building CXX object src/CMakeFiles/bustub_shared.dir/type/decimal_type.cpp.o
[ 84%] Building CXX object src/CMakeFiles/bustub_shared.dir/type/integer_parent_type.cpp.o
[ 86%] Building CXX object src/CMakeFiles/bustub_shared.dir/type/integer_type.cpp.o
[ 88%] Building CXX object src/CMakeFiles/bustub_shared.dir/type/smallint_type.cpp.o
[ 90%] Building CXX object src/CMakeFiles/bustub_shared.dir/type/timestamp_type.cpp.o
[ 92%] Building CXX object src/CMakeFiles/bustub_shared.dir/type/tinyint_type.cpp.o
[ 94%] Building CXX object src/CMakeFiles/bustub_shared.dir/type/type.cpp.o
[ 96%] Building CXX object src/CMakeFiles/bustub_shared.dir/type/value.cpp.o
[ 98%] Building CXX object src/CMakeFiles/bustub_shared.dir/type/varlen_type.cpp.o
[100%] Linking CXX shared library ../lib/libbustub_shared.so
[100%] Built target bustub_shared

Scanning dependencies of target check-format
--- /autograder/bustub/src/storage/page/b_plus_tree_leaf_page.cpp
+++ /autograder/bustub/src/storage/page/b_plus_tree_leaf_page.cpp (after clang format)
@@ -43,9 +43,7 @@
 page_id_t B_PLUS_TREE_LEAF_PAGE_TYPE::GetNextPageId() const { return next_page_id_; }
 
 INDEX_TEMPLATE_ARGUMENTS
-void B_PLUS_TREE_LEAF_PAGE_TYPE::SetNextPageId(page_id_t next_page_id) {
-  next_page_id_ = next_page_id;
-}
+void B_PLUS_TREE_LEAF_PAGE_TYPE::SetNextPageId(page_id_t next_page_id) { next_page_id_ = next_page_id; }
 
 /**
  * Helper method to find the first index i so that array[i].first >= key
@@ -53,12 +51,13 @@
  */
 INDEX_TEMPLATE_ARGUMENTS
 int B_PLUS_TREE_LEAF_PAGE_TYPE::KeyIndex(const KeyType &key, const KeyComparator &comparator) const {
-  for(int i=0; i < GetSize(); i++){
-    if (comparator(array[i].first, key) >=0 ){
+  for (int i = 0; i < GetSize(); i++) {
+    if (comparator(array[i].first, key) >= 0) {
       return i;
     }
   }
-  return -1; }
+  return -1;
+}
 ...

My code can run in my local and I have passed the test on project1 on gradescope. I have no idea what is wrong.

**Comment by lmwnshn** [comment]
https://15445.courses.cs.cmu.edu/fall2020/faq.html#q6

**Comment by JunfengZZZZhou** [comment]
> 
> 
> https://15445.courses.cs.cmu.edu/fall2020/faq.html#q6

It shows "valgrind: ./grading_b_plus_tree_checkpoint_1_test: No such file or directory" which is not the file I submitted. I think it's a system problem.
