### ISSUE TITLE
Memory Safety Test

### ISSUE THREAD

**Issue by yewenw** [cmu-db/bustub#144]
Hello, I was not able to pass the test_memory_safety test in Project #2 - Checkpoint #1, and am wondering what could be the cause of the memory leak. Any ideas? Thanks. 

![Screen Shot 2021-03-17 at 7 50 00 PM](https://user-images.githubusercontent.com/53163614/111566256-11c71c00-875a-11eb-9230-cd0b8b6de4a9.png)

**Comment by lmwnshn** [comment]
https://15445.courses.cs.cmu.edu/fall2020/faq.html#q6
