### ISSUE TITLE
Are we assuming no endianness?

### ISSUE THREAD

**Issue by evanxg852000** [cmu-db/bustub#146]
https://github.com/cmu-db/bustub/blob/14922dc6ddddaba311b7bdcba1bea48ce8d38810/src/type/integer_type.cpp#L271
I have been reading/learning this code but I could not find anywhere taking into account machine endianness. My guess is that since this is educational, we assume that the db file will be used on the same machine. I just need to confirm it or point me to explain how endianness is handled here if any.
Thanks

**Comment by apavlo** [comment]
You are correct that we are not dealing with endianness. This is not meant to be super robust for different CPU architectures.

**Comment by evanxg852000** [comment]
Thanks for clarifying, thanks a lot for these wonderful materials too.
