### ISSUE TITLE
build_support/packages.sh and make fails on M1 Mac(Apple Silicon)

### ISSUE THREAD

**Issue by seastar105** [cmu-db/bustub#153]
Since there's no `-march` flag in arm_x64_clang, and brew has no llvm@8 runs on apple silicon, build fails. 

is it necessary to use llvm@8 instead of any upper version of llvm(11, 12)?

**Comment by csphile** [comment]
Meet the same issue too: 
`clang: error: the clang compiler does not support '-march=native'
`

**Comment by ZonePG** [comment]
just delete CMakefile.txt at 80 line build flag `-march=native`

**Comment by whalekawhi** [comment]
if you have clang version 13.0.0, replace build flag `-march=native` on line 81 in CMakeLists.txt to `-mcpu=apple-m1`

**Comment by skyzh** [comment]
Should have been fixed by https://github.com/cmu-db/bustub/pull/243?

**Comment by fengxiaohu** [comment]
**same problem on M1**
I replace the -march=native on line 81 in CMakeLists.txt to -mcpu=apple-m1,However when I run this command
`cmake ..`
erro like this 
```
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:42 (message):
  BusTub/main couldn't find clang-format.


CMake Warning at CMakeLists.txt:55 (message):
  BusTub/main couldn't find clang-tidy.


-- BusTub/main found cpplint at /Users/xiaohufeng/Documents/public-bustub/build_support/cpplint.py
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xiaohufeng/Documents/public-bustub/build/googletest-download
[ 11%] Creating directories for 'googletest'
[ 22%] Performing download step (git clone) for 'googletest'
Cloning into 'googletest-src'...
fatal: invalid reference: master
CMake Error at googletest-download/googletest-prefix/tmp/googletest-gitclone.cmake:49 (message):
  Failed to checkout tag: 'master'


make[2]: *** [googletest-prefix/src/googletest-stamp/googletest-download] Error 1```

make[1]: *** [CMakeFiles/googletest.dir/all] Error 2
make: *** [all] Error 2
CMake Error at CMakeLists.txt:79 (add_subdirectory):
  The source directory

    /Users/xiaohufeng/Documents/public-bustub/build/googletest-src

  does not contain a CMakeLists.txt file.


-- CMAKE_CXX_FLAGS:  -Wno-unused-parameter -Wno-attributes
-- CMAKE_CXX_FLAGS_DEBUG: -g -O0 -ggdb -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls
-- CMAKE_EXE_LINKER_FLAGS:  -fPIC
-- CMAKE_SHARED_LINKER_FLAGS:  -fPIC
CMake Warning at test/CMakeLists.txt:10 (message):
  BusTub/test couldn't find valgrind.


-- Configuring incomplete, errors occurred!
```
I think it may be the lack of googletest,So I install the google test `brew intall googletest`

**Comment by skyzh** [comment]
As seen in the log, cmake didn't successfully download google test. You don't have to install it by yourself -- cmake will take care of it.

**Comment by fengxiaohu** [comment]
> As seen in the log, cmake didn't successfully download google test. You don't have to install it by yourself -- cmake will take care of it.

OK,thx for reply.So how do I solve this problem,have you ever succeed building bustub in M1 mac?,can you give me some ideas or solutions

**Comment by skyzh** [comment]
You will need a better network. I succeeded without any extra configuration.

**Comment by fengxiaohu** [comment]
aha ,I found googletest modify the master tag,So the git clone failed.
https://github.com/google/googletest/issues/3663
modify the 8 line in build_support/gtest_CMakelist 
`GIT_TAG master` to `GIT_TAG main`

**Comment by skyzh** [comment]
It's already main. Are you using the latest main branch?

https://github.com/cmu-db/bustub/blob/8ec6039d3c7129c8b7e8209b6a7fba2dc2c4dddf/build_support/gtest_CMakeLists.txt.in#L6-L15

**Comment by skyzh** [comment]
Feel free to reopen if you have further questions 🥰
