### ISSUE TITLE
Buffer pool manager test problem

### ISSUE THREAD

**Issue by Zhaotianzheng** [cmu-db/bustub#158]
```
 // Scenario: After unpinning pages {0, 1, 2, 3, 4} and pinning another 4 new pages,
  // there would still be one cache frame left for reading page 0.
  for (int i = 0; i < 5; ++i) {
    EXPECT_EQ(true, bpm->UnpinPage(i, true));
    bpm->FlushPage(i);
  }
  for (int i = 0; i < 5; ++i) {
    EXPECT_NE(nullptr, bpm->NewPage(&page_id_temp));
    bpm->UnpinPage(page_id_temp, false);
  }
```
This is the code I see in the test cpp file, and I think the second for loop should be terminated at 3. I don't if I get it wrong....Or I just asked a silly question..

**Comment by skyzh** [comment]
The comments are updated in https://github.com/cmu-db/bustub/pull/175. The latest code is like:

https://github.com/cmu-db/bustub/blob/8ec6039d3c7129c8b7e8209b6a7fba2dc2c4dddf/test/buffer/buffer_pool_manager_instance_test.cpp#L66-L74

Therefore, the test case at first fill the whole buffer pool, then unpin 5 pages, and now we have 5 slots free. Therefore the second loop will continue without assertion failure.

Shall we close this issue?

**Comment by skyzh** [comment]
Feel free to reopen if you have further questions 😊
