### ISSUE TITLE
Encounter compiling error under  gcc 10.3.0 

### ISSUE THREAD

**Issue by MedivhGO** [cmu-db/bustub#164]
at src/type/decimal_type.cpp line 301

if (val.GetAs< double >() > BUSTUB_INT64_MAX || val.GetAs< double >() < BUSTUB_INT64_MIN) {

Implicit conversion from 'const int64_t' (aka 'const long') to 'double' changes value from 9223372036854775807 to 9223372036854775808

This page explained  the reason.

https://stackoverflow.com/questions/691935/convert-int64-t-to-double.

**Comment by apavlo** [comment]
Can you please send a PR with the fix? Thanks

**Comment by iwanttobepowerful** [comment]
![image](https://user-images.githubusercontent.com/30350667/131597333-fab41e0e-bbcf-4bd0-b2d4-80ed27b3d126.png)

**Comment by iwanttobepowerful** [comment]
![image](https://user-images.githubusercontent.com/30350667/131597416-71bdb3ff-aa5b-419b-af65-38f7afc9ae32.png)

**Comment by MedivhGO** [comment]
#165 @apavlo

**Comment by garrisonhess** [comment]
Fixed in #165 thanks @MedivhGO
