### ISSUE TITLE
check-lint assumes python is symlinked to python2

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/bustub#17]
If this happens to you

```
$ make check-lint
Scanning dependencies of target check-lint
make[3]: *** [CMakeFiles/check-lint] Error 1
make[2]: *** [CMakeFiles/check-lint.dir/all] Error 2
make[1]: *** [CMakeFiles/check-lint.dir/rule] Error 2
make: *** [check-lint] Error 2
```

i.e. check-lint doesn't seem to show you any errors, the reason is because Google's [cpplint](https://github.com/cpplint/cpplint) assumes that `python` will run `python2`. More specifically, the `python` first found in your `PATH` must be `python2`.

The workaround is to run `PATH=/usr/bin:$PATH make check-lint`. On most operating systems with `python` symlinked to `python2`, this should work. If you're running Arch Linux or something else with `python` symlinked to `python3`, you should know how to fix it yourself.

I've been meaning to convert their script to work with Python 3, but I don't have the time. A good first step is probably running [2to3](https://docs.python.org/3.7/library/2to3.html) on it.

If you fix this issue, your fix will be ported to [terrier](https://github.com/cmu-db/terrier) which faces the same problem. I think Apache Arrow might have similar cpplint issues too.

**Comment by louchenyao** [comment]
Maybe you can consider using this forked [cpplint](https://github.com/cpplint/cpplint).

**Comment by lmwnshn** [comment]
Happy to accept any PRs... :P

**Comment by charlesfranciscodev** [comment]
same issue here on Ubuntu 20.04, thanks for the help

**Comment by skyzh** [comment]
Already resolved with https://github.com/cmu-db/bustub/pull/243. It's now using Python3 by default.

https://github.com/cmu-db/bustub/blob/8ec6039d3c7129c8b7e8209b6a7fba2dc2c4dddf/build_support/cpplint.py#L1
