### ISSUE TITLE
/test/buffer/lru_replacer_test.cpp  may be wrong！

### ISSUE THREAD

**Issue by MerickBao** [cmu-db/bustub#182]
this file is to test the 「lru_replacer」，and in it's source code :
```c++
TEST(LRUReplacerTest, SampleTest) {
  LRUReplacer lru_replacer(7);

  // Scenario: unpin six elements, i.e. add them to the replacer.
  lru_replacer.Unpin(1);
  lru_replacer.Unpin(2);
  lru_replacer.Unpin(3);
  lru_replacer.Unpin(4);
  lru_replacer.Unpin(5);
  lru_replacer.Unpin(6);
  lru_replacer.Unpin(1); // last add 1
  EXPECT_EQ(6, lru_replacer.Size());

  // Scenario: get three victims from the lru.
  int value;
  lru_replacer.Victim(&value);
  EXPECT_EQ(1, value); // I think there is should be 2 
  lru_replacer.Victim(&value);
  EXPECT_EQ(2, value);
  lru_replacer.Victim(&value);
  EXPECT_EQ(3, value);
```
Because the number 1 was added last, I think it is the most recently used, so the first removal should be 2.
did i misunderstand the LRU replace policy?

**Comment by apavlo** [comment]
Page1 was unpinned twice. Why would it's position change?

**Comment by apavlo** [comment]
Also: https://15445.courses.cs.cmu.edu/fall2021/faq.html#q8

**Comment by MerickBao** [comment]
I am a Chinese student and I like your course very much. And I'm sorry I didn't read this rule before, now I have joined the discord group.
