### ISSUE TITLE
IntComparator overflow risk

### ISSUE THREAD

**Issue by Aureliano98** [cmu-db/bustub#184]
IntComparator could yield incorrect results due to overflow. For example, IntComparator()(INT_MIN, INT_MAX) == 1, but it should be -1 (or any negative number):

https://github.com/cmu-db/bustub/blob/d3cea79bbe49e9daa16c1be081dbc3bd6eb6dbad/src/include/storage/index/int_comparator.h#L17-L24

Also (though slightly off topic), it would be better to mark the member function as const to be consistent with GenericComparator and STL comparators.

**Comment by apavlo** [comment]
Thanks for posting this. Can you send us a patch?
