### ISSUE TITLE
extendible_hash_table.h#L122 return type should be page_id_t

### ISSUE THREAD

**Issue by iwanttobepowerful** [cmu-db/bustub#187]
@garrisonhess  [inline uint32_t KeyToPageId(KeyType key, HashTableDirectoryPage *dir_page);](https://github.com/cmu-db/bustub/blob/a426a1082854abf8f7cb9594dad727fc2ebb6a18/src/include/container/hash/extendible_hash_table.h?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L122)   return type should be page_id_t

**Comment by wandersofb** [comment]
Why don't fix this question? Any reason?

**Comment by wandersofb** [comment]
@garrisonhess
