### ISSUE TITLE
maybe imported unnecessary code in bustub/src/include/storage/page/hash_table_block_page.h

### ISSUE THREAD

**Issue by iwanttobepowerful** [cmu-db/bustub#193]
@garrisonhess [96~139 lines, I think its unnecessary. That should belong to `src/include/storage/page/hash_table_bucket_page.h`](https://github.com/cmu-db/bustub/blob/34c7145d2698be0142640801947a05fe9bb9142d/src/include/storage/page/hash_table_block_page.h?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L101)  Thx.

**Comment by garrisonhess** [comment]
These are separate because they are for different kinds of hash indexes.
