### ISSUE TITLE
Why both HashTableBucketPage and HashTableBlockPage do not have header that can store such as LSN?

### ISSUE THREAD

**Issue by iwanttobepowerful** [cmu-db/bustub#196]
@apavlo

**Comment by sunznx** [comment]
I met same bug here?
1. NewPage from buffer pool and set Page LSN = INVALID_LSN (-1)
2. Set the `HashTableBucketPage` by `reinterpret_cast< HashTableBucketPage *>(page->GetData())`
3. `HashTableBucketPage` member variable will be assigned as (-1)

**Comment by iwanttobepowerful** [comment]
Maybe the original design is right.
