### ISSUE TITLE
Can't run ./packages.sh on Arch Linux

### ISSUE THREAD

**Issue by sauntheninja2** [cmu-db/bustub#198]
`Unsupported distribution 'LINUX'
Please contact our support team for additional help.
Be sure to include the contents of this message.
Platform: Linux sujay 5.14.16-arch1-1 #1 SMP PREEMPT Tue, 02 Nov 2021 22:22:59 +0000 x86_64 GNU/Linux
`

**Comment by lmwnshn** [comment]
Arch linux is not officially supported. You can modify packages.sh if you want to try getting around it, but no support guarantees there.
