### ISSUE TITLE
Project1 on GradeScope suffers from timed out.

### ISSUE THREAD

**Issue by YihaoChan** [cmu-db/bustub#200]
When I tested on project1 on GradeScope, I suffered from TIMEDOUT. I also tested solely on LRUReplacer, and made the other parts(BufferPoolInstance, ParallelBufferPool) default, but it still turned out to be timedout... I'm sure that my LRUReplacer doesn't have dead lock, and it's simply implemented. In addition, all three parts are passed offline. So does anyone encounter this? Or could anyone give some advice to fix it? Thanks!
![image](https://user-images.githubusercontent.com/60082669/141310665-5f7b0cf3-2cc2-45f3-8110-8e327b366d24.png)

**Comment by lmwnshn** [comment]
https://15445.courses.cs.cmu.edu/fall2021/faq.html#q8

**Comment by YihaoChan** [comment]
> https://15445.courses.cs.cmu.edu/fall2021/faq.html#q8

I had been asking it on Discord for several days, but no one replied. Actually, to be honest, the talking on Discord is not that good.

**Comment by epis2048** [comment]
Make sure you have run the following two commands:

```
make check-lint
make check-clang-tidy
```

and passed its inspection
