### ISSUE TITLE
Building GoogleTest with CMake in Bustub repo

### ISSUE THREAD

**Issue by nrd10** [cmu-db/bustub#205]
The GoogleTest repo "master" branch was now renamed to "main". As a result calling "cmake .." in the build directory will no longer work. 

The file "build_support/gtest_CMakeLists.txt.in" needs to be updated to the following:
GIT_TAG main

**Comment by lmwnshn** [comment]
I thought this was fixed in #203?

**Comment by lmwnshn** [comment]
Please reopen if it isn't.

**Comment by EtoDemerzel0427** [comment]
@lmwnshn It is fixed here, but seems not fixed for the Non-CMU student Gradescope, so that we are unable to test our works. Could you please check that?
