### ISSUE TITLE
Unable to register in gradescope for non CMU students

### ISSUE THREAD

**Issue by ax7e** [cmu-db/bustub#210]
When I tried to register on the gradescope website, it prompts me that the code is invalid.
![image](https://user-images.githubusercontent.com/53501747/148169428-8840a2d8-2d7a-425d-913b-4b79014374e3.png)

**Comment by apavlo** [comment]
What year is this? Are you using your university email address?

**Comment by ltomic** [comment]
I ran into the same issue today. The code 4PR8G5 should be for year 2021 as stated [here](https://15445.courses.cs.cmu.edu/fall2021/faq.html#q7). I have also tried the code for year 2020 which can be found [here](https://15445.courses.cs.cmu.edu/fall2020/faq.html#q5) and ran into the same issue.

I am using my university email address.

**Comment by apavlo** [comment]
@ltomic @ax7e I think Gradescope blocks you try to register with a non-CMU edu address. Try a fake/personal email.

**Comment by Robbery-NEU** [comment]
I met with the same problem today,is there any new entry code?

**Comment by ltomic** [comment]
I managed to sign-up. The school that should be picked is Carnegie Mellon University. What I did wrong before is picking the school I was enrolled in.

**Comment by ax7e** [comment]
Great job! I think this information should be updated in the course page.
