### ISSUE TITLE
BufferPoolManagerInstanceTest does not test for thread-safety

### ISSUE THREAD

**Issue by Anarion-zuo** [cmu-db/bustub#215]
The tests provided in Project 1 does not test for thread-safety, while it is required to write thread-safe code. Do I have to write some tests myself, or will this problem be resolved in later projects?

**Comment by apavlo** [comment]
Did you test it on Gradescope? The grading tests check for concurrency bugs.

https://15445.courses.cs.cmu.edu/fall2021/faq.html#q7

**Comment by Anarion-zuo** [comment]
I am not a student of CMU, so I am unable to do that. I followed you on YouTube and find your courses especially helpful. Thank you for your noble work!

**Comment by Anarion-zuo** [comment]
I figured out how to use gradescope. Thank you again!
