### ISSUE TITLE
have a question about the "DEADLOCK PREVENTION"

### ISSUE THREAD

**Issue by sunznx** [cmu-db/bustub#217]
see we have two transactions, and txn2 will abort txn1 at t2 as "DEADLOCK PREVENTION";
But txn1 is not aware that it has been aborted at this point. so txn1 still thinks it holds the lock, and it updates the Rid at t3.

In this project, the above results are inconsistent
![image](https://user-images.githubusercontent.com/8629792/152276159-d56697ae-4dd0-4a30-acf1-99d1f9fc3311.png)

**Comment by Tusen183** [comment]
hey,guy.I have the same question with you.Did you figure out it?

**Comment by sunznx** [comment]
> Did you figure out it?
no.

**Comment by Tusen183** [comment]
I think the test assumes that acquiring locks and wound wait are at the same granularity.

**Comment by sunznx** [comment]
this looks like to be a bug that requires implementation of MVCC to fix?
no one cared, so I close this issue

**Comment by Tusen183** [comment]
It's hard to say.My friend pass All TEST
