### ISSUE TITLE
Project2: the comment does not match the code regarding BUCKET_ARRAY_SIZE.

### ISSUE THREAD

**Issue by Ao-Last** [cmu-db/bustub#219]
### src/include/storage/page/hash_table_page_defs.h
![image](https://user-images.githubusercontent.com/63785048/152676765-5987a02e-7a24-45b7-9d49-6c460da3d09a.png)

**Comment by garrisonhess** [comment]
This was a typo in the comment and is fixed now.  Thanks for spotting it.  Marking as resolved.
