### ISSUE TITLE
Googletest build failed on Gradescope

### ISSUE THREAD

**Issue by PrettyMeng** [cmu-db/bustub#225]
Hi there,

I failed to build Googletest on Gradescope, which I believe is an error on the server side. I test a previous submission that was successfully built on Gradescope but it fails now. The error message is as below: 

/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest.h:1352:11: error: The left operand of '==' is a garbage value [clang-analyzer-core.UndefinedBinaryOperatorResult,-warnings-as-errors]
  if (lhs == rhs) {
          ^
/autograder/bustub/test/storage/grading_tmp_tuple_page_test.cpp:101:3: note: Control jumps to 'case 0:'  at line 101
  ASSERT_EQ(*reinterpret_cast<page_id_t *>(data), page_id);
  ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest.h:1869:31: note: expanded from macro 'ASSERT_EQ'
#define ASSERT_EQ(val1, val2) GTEST_ASSERT_EQ(val1, val2)
                              ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest.h:1853:3: note: expanded from macro 'GTEST_ASSERT_EQ'
  ASSERT_PRED_FORMAT2(::testing::internal::EqHelper::Compare, val1, val2)
  ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest_pred_impl.h:148:3: note: expanded from macro 'ASSERT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_FATAL_FAILURE_)
  ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest_pred_impl.h:134:3: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), on_failure)
  ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest_pred_impl.h:78:3: note: expanded from macro 'GTEST_ASSERT_'
  GTEST_AMBIGUOUS_ELSE_BLOCKER_                                 \
  ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/internal/gtest-port.h:644:3: note: expanded from macro 'GTEST_AMBIGUOUS_ELSE_BLOCKER_'
  switch (0)                          \
  ^
/autograder/bustub/test/storage/grading_tmp_tuple_page_test.cpp:101:3: note: Calling 'EqHelper::Compare'
  ASSERT_EQ(*reinterpret_cast<page_id_t *>(data), page_id);
  ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest.h:1869:31: note: expanded from macro 'ASSERT_EQ'
#define ASSERT_EQ(val1, val2) GTEST_ASSERT_EQ(val1, val2)
                              ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest.h:1853:23: note: expanded from macro 'GTEST_ASSERT_EQ'
  ASSERT_PRED_FORMAT2(::testing::internal::EqHelper::Compare, val1, val2)
                      ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest_pred_impl.h:148:23: note: expanded from macro 'ASSERT_PRED_FORMAT2'
  GTEST_PRED_FORMAT2_(pred_format, v1, v2, GTEST_FATAL_FAILURE_)
                      ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest_pred_impl.h:134:17: note: expanded from macro 'GTEST_PRED_FORMAT2_'
  GTEST_ASSERT_(pred_format(#v1, #v2, v1, v2), on_failure)
                ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest_pred_impl.h:79:52: note: expanded from macro 'GTEST_ASSERT_'
  if (const ::testing::AssertionResult gtest_ar = (expression)) \
                                                   ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest.h:1371:56: note: Passing value via 3rd parameter 'lhs'
    return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
                                                       ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest.h:1371:12: note: Calling 'CmpHelperEQ<int, int>'
    return CmpHelperEQ(lhs_expression, rhs_expression, lhs, rhs);
           ^
/autograder/bustub/build/googletest-src/googletest/include/gtest/gtest.h:1352:11: note: The left operand of '==' is a garbage value
  if (lhs == rhs) {
          ^
The files that failed were:
[u'/autograder/bustub/test/storage/tmp_tuple_page_test.cpp',
 u'/autograder/bustub/test/storage/grading_tmp_tuple_page_test.cpp']
Note that a failing .h file will fail all the .cpp files that include it.

CMakeFiles/check-clang-tidy.dir/build.make:57: recipe for target 'CMakeFiles/check-clang-tidy' failed
make[3]: *** [CMakeFiles/check-clang-tidy] Error 1
CMakeFiles/Makefile2:164: recipe for target 'CMakeFiles/check-clang-tidy.dir/all' failed
make[2]: *** [CMakeFiles/check-clang-tidy.dir/all] Error 2
CMakeFiles/Makefile2:171: recipe for target 'CMakeFiles/check-clang-tidy.dir/rule' failed
make[1]: *** [CMakeFiles/check-clang-tidy.dir/rule] Error 2
Makefile:214: recipe for target 'check-clang-tidy' failed
make: *** [check-clang-tidy] Error 2

Any help would be appreciated. Thanks!

**Comment by PrettyMeng** [comment]
An additional note: this failure happens for project 0 and project 3. It does not happen for project 1, not sure why this is the case.

**Comment by Axsl666** [comment]
I encountered the same problem in project 0.

**Comment by apavlo** [comment]
@PrettyMeng What course semester are you testing?

**Comment by PrettyMeng** [comment]
> @PrettyMeng What course semester are you testing?

The latest version, which is Fall 2021

**Comment by ptbxzrt** [comment]
I encountered the same problem in project 3, query execution.

**Comment by billservice** [comment]
Have the same issue for Fall 2020.

**Comment by cquludajun** [comment]
Happened to me too.  
The local check-clang-tidy failed too with similar logs.  The failed build was run using the docker image provided by the course.

**Comment by DYH-Hong** [comment]
I've tried clang-tidy 8, 10 and 13 on my Ubuntu 20.04.

Strangely, clang-tidy 10 is pretty silent, while clang-tidy 8 and 13 throw a huge amount of problems in GTest code.

**Comment by PrettyMeng** [comment]
> > @PrettyMeng What course semester are you testing?
> 
> The latest version, which is Fall 2021

@apavlo In case you missed the message : )

**Comment by ptbxzrt** [comment]
@PrettyMeng Hello bro, I wonder wheather the problem solved or not?thanks

**Comment by Shmiwy** [comment]
I encountered the same problem in project 2，3，4（2020 fall）

**Comment by bencwallace** [comment]
I'm running into the same problem when running `make check-clang-tidy` locally on the master branch.

**Comment by Carolforever** [comment]
when will it be fixed...

**Comment by lihao-github-create** [comment]
> > 
> 
> > @PrettyMeng Hello bro, I wonder wheather the problem solved or not?thanks
> 
> No. Everyone uses the same Gradescope server and I believe this is not an error that we can fix locally.

Has this problem been solved?

**Comment by ptbxzrt** [comment]
> 

For 2021-project3, I think problem has not been solved.

**Comment by 18813151705** [comment]
Same problem with project2, Fall 2021.

**Comment by Ahbbq** [comment]
Same problem with project2, Fall-2021.

**Comment by chenzeyin9867** [comment]
Encounter sam bug in project0, Fall-2021, when can this be fixed?

**Comment by apavlo** [comment]
I don't have a TAs available to work on this now and I won't have time to look at this until later in the week. If somebody can provide a fix, I can update Gradescope.
