### ISSUE TITLE
Build Failed in project 2

### ISSUE THREAD

**Issue by chenzeyin9867** [cmu-db/bustub#230]
I passed all the local tests include the format checking, but when i move to graderscope, the build test reports like this.

![0ae33af1b45f56a01675b3d4b1d1933](https://user-images.githubusercontent.com/48000404/161370829-66ea6908-78a5-49e4-a948-e7fa2db9af48.png)

There was no other fails, is there anyone who encountered the same problem?

**Comment by mxysfive** [comment]
hey bro, i encontered the same issuse, it looks like the issuse is caused by googletest(maybe), The autograde version i use is 2020Fall.

**Comment by skyzh** [comment]
https://github.com/cmu-db/bustub/issues/227
