### ISSUE TITLE
Project 1. For Apple M1

### ISSUE THREAD

**Issue by kaiseryyd** [cmu-db/bustub#231]
clang: error: the clang compiler does not support '-march=native'

**Comment by kaiseryyd** [comment]
> 
Thanks! successfully resolved

**Comment by kaiseryyd** [comment]
> Solution: replace build flag -march=native on line 81 in CMakeLists.txt to -mcpu=apple-m1, this will solve the problem.
> 
> btw, since the code has a conversion between int64_t and double, clang 15.0.0 will not compile the code

Thanks! successfully resolved

**Comment by marxhxxx** [comment]
For my case, I simply delete the -march=native and worked.

**Comment by garrisonhess** [comment]
Resolved in #243
