### ISSUE TITLE
Do we need to check the original code

### ISSUE THREAD

**Issue by PhzCode** [cmu-db/bustub#232]
In project1, I finish and upload my code, but `[test_memory_safety]()` checkpoint can not pass. And then I review the code, modify the code  at Line 41 in file `src/buffer/buffer_pool_manager_instance.cpp`, and pass the checkpoint. Is this line for the checkpoint specially that need we modify? If so, I will delete this issue immediately.
```C++
  // before
  for (size_t i = 0; i < pool_size_; ++i) {
    free_list_.emplace_back(static_cast<int>(i));
  }

  // after 
  for (size_t i = 0; i < pool_size_; ++i) {
    free_list_.emplace_back(static_cast<frame_id_t>(i));
  }
```

**Comment by skyzh** [comment]
I think it's more of some random chances that this change magically makes some of your bugs not visible in tests. Better to check your code instead of changing the skeleton.
