### ISSUE TITLE
“YOU HAVE 1 DISABLED TEST”

### ISSUE THREAD

**Issue by DeepZheng** [cmu-db/bustub#233]
I am doing the first lab project and running "lru_replacer_test". And it tells me "YOU HAVE 1 DISABLED TEST" while there are 0 test cases.
Is there something wrong with my code or just a common problem that I can ignore it? 
Here's the screenshot
![image](https://user-images.githubusercontent.com/52077399/163706415-1b1bed98-340e-4d13-807e-533826996cb9.png)

**Comment by zhangruian** [comment]
You should remove the "DISABLED_" prefix，such as "DISABLED_SampleTest" in src/test/buffer/lru_replacer_test.cpp

**Comment by DeepZheng** [comment]
> You should remove the "DISABLED_" prefix，such as "DISABLED_SampleTest" in src/test/buffer/lru_replacer_test.cpp

Awesome ！THANKS ！

**Comment by li-cr** [comment]
> > You should remove the "DISABLED_" prefix，such as "DISABLED_SampleTest" in src/test/buffer/lru_replacer_test.cpp
> 
> Awesome ！THANKS ！

Awesome ！THANKS ！
