### ISSUE TITLE
redistribute condition

### ISSUE THREAD

**Issue by chaomaer** [cmu-db/bustub#235]
https://github.com/cmu-db/bustub/blob/ed3fdb6a71e23051d91d1c14dad6385d3e44f213/src/storage/index/b_plus_tree.cpp#L123

`If sibling's size + input  page's size > page's max size, then redistribute. `
Is the '>' should be '>=', or when merging two pages, the size of one node may be the max size, which needs one split operation.

**Comment by skyzh** [comment]
See course slides for more information. It depends.
