### ISSUE TITLE
project0 build failed

### ISSUE THREAD

**Issue by gxsoar** [cmu-db/bustub#239]
I can build the project0 on my wsl successfully and pass the test, however,when i submit the file to the gradescope, it build unsuccesfully.
![image](https://user-images.githubusercontent.com/47854660/168027114-c9f21a4c-7256-429c-88e2-760ad75a9a7f.png)

**Comment by zhouhuahui** [comment]
I have encountered the same problem, have you solved this yet?

**Comment by ZRH20001004** [comment]
Have you solved this yet?

**Comment by greenhandzpx** [comment]
Same problem.

**Comment by dliang5** [comment]
I was able to submit my p0 to gradescope just now and it seems to be working fine. You might want to copy and paste that message onto a text editor to see what is wrong. I originally didn't implement GEMM correctly which isn't included in the given test suite.

**Comment by ZRH20001004** [comment]
thanks




| |
zrh20001004
|
|
***@***.***
|
---- Replied Message ----
| From | David ***@***.***> |
| Date | 6/2/2022 09:29 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [cmu-db/bustub] project0 build failed (Issue #239) |

I was able to submit my p0 to gradescope just now and it seems to be working fine. You might want to copy and paste that message onto a text editor to see what is wrong. I originally didn't implement GEMM correctly which isn't included in the given test suite.

**Comment by skyzh** [comment]
Please wait for our new gradescope for 2022 Fall. See https://github.com/cmu-db/bustub/issues/227 for more information. Thanks!
