### ISSUE TITLE
starter_test.cpp cannot catch ExceptionType in InitializationTest

### ISSUE THREAD

**Issue by ctxdata** [cmu-db/bustub#247]
./test/starter_test will crash after enabling InitializationTest.

```
unknown file: Failure
Unknown C++ exception thrown in the test body.
[  FAILED  ] StarterTest.InitializationTest (33137 ms)
[ DISABLED ] StarterTest.DISABLED_ElementAccessTest
[ DISABLED ] StarterTest.DISABLED_AdditionTest
[ DISABLED ] StarterTest.DISABLED_MultiplicationTest
[----------] 2 tests from StarterTest (33137 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (33137 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] StarterTest.InitializationTest
```

The root cause is ThrowsBustubException won't catch ExceptionType, it catches `const Exception&` instead. While in RowMatrix<T>::FillFrom specification, implementor must throw ExceptionType::OUT_OF_RANGE if the size is mismatched.

To fix the issue, we should catch ExceptionType in ThrowsBustubException

```
catch (const ExceptionType &et) {
    expected_type_thrown = et == type;
  }
```

**Comment by skyzh** [comment]
2021 Fall's p0 is not maintained any more. We'll remove it soon.
