### ISSUE TITLE
UT parallel_buffer_pool_manager_test.cpp is not correct

### ISSUE THREAD

**Issue by ctxdata** [cmu-db/bustub#250]
[Refer code](https://github.com/cmu-db/bustub/blob/8bb470b919d80c9422beac9091f8cdc2ec3c95af/test/buffer/parallel_buffer_pool_manager_test.cpp#L130)

Line 130 will always fail because page_id:4 was unpinned at line 124.

```
~/bustub/test/buffer/parallel_buffer_pool_manager_test.cpp:130: Failure
Expected equality of these values:
  true
  bpm->UnpinPage(i, true)
    Which is: false
```

From the context of unit test, I think line 124 should be removed.

Best Regards,

**Comment by skyzh** [comment]
I think that's the confusing caused by replacer APIs. We've changed a lot. If you still have questions, go to GitHub Discussion and create an Q&A.
