### ISSUE TITLE
Question about ReaderWriterLatch

### ISSUE THREAD

**Issue by alkaid0815** [cmu-db/bustub#254]
Is it correct to add ` if (reader_count_ == MAX_READERS - 1)` ? 
For example, there are two threads called Rlock() blocked in `reader_.wait(latch)` because of `reader_count_ == MAX_READERS`. then the RUnlock() is called by another thread, `if (reader_count_ == MAX_READERS - 1) {
        reader_.notify_one();
      }` this if statement is true, then notify_one(), however, notify_one is just only awake one blocked thread(means it could be scheduled by scheduler, not immediately switch to the waiting thread and continue execute the wait()). So if there is another RUnlock() call before the wait() is called, then the ` if (reader_count_ == MAX_READERS - 1)` is false, so there will be a missing call to `reader_.notify_one()`. The result is only one thread is awaked but it should be two threads being awaked.

```c++
/**
   * Acquire a read latch.
   */
  void RLock() {
    std::unique_lock<mutex_t> latch(mutex_);
    while (writer_entered_ || reader_count_ == MAX_READERS) {
      reader_.wait(latch);
    }
    reader_count_++;
  }

  /**
   * Release a read latch.
   */
  void RUnlock() {
    std::lock_guard<mutex_t> guard(mutex_);
    reader_count_--;
    if (writer_entered_) {
      if (reader_count_ == 0) {
        writer_.notify_one();
      }
    } else {
      if (reader_count_ == MAX_READERS - 1) {
        reader_.notify_one();
      }
    }
  }
```

**Comment by skyzh** [comment]
Looks reasonable to me! I'm thinking of a fix...

**Comment by skyzh** [comment]
But I think it's rare case that we will hit `MAX_READERS` -- it's `UINT_MAX` for now. I believe this bug is easier to be reproduced if we set `MAX_READERS` to a smaller value...
