### ISSUE TITLE
llvm@8 build error

### ISSUE THREAD

**Issue by sagnik3** [cmu-db/bustub#255]
OS: macOS version 12.4
Hardware Architecture : Mac M1

While using the packages.sh script to download the dependencies , it says that llvm@8 is failing due to being dependent of the x86_64 architecture. How to overcome this build error ?

**Comment by sagnik3** [comment]
Closing this as this is a duplicate of #153 .

**Comment by skyzh** [comment]
Should use llvm@12 instead, as specified in package.sh.
