### ISSUE TITLE
RFC: parser, binder, planner and interactive shell for bustub

### ISSUE THREAD

**Issue by skyzh** [cmu-db/bustub#257]
I just realized that bustub doesn't have an interactive shell (or accept SQL statements) like other database systems do. From my perspective, this might make it a little bit hard for students to have a complete overview of how a relational database system looks like. Students cannot use SQL queries to test out their own changes. They have to manually construct query plans (which is prune to error!) to test the implementation of executors. Examples:

https://github.com/cmu-db/bustub/blob/8ec6039d3c7129c8b7e8209b6a7fba2dc2c4dddf/test/execution/executor_test.cpp#L592-L618

I'm thinking of introducing a very simple parser, binder and planner framework to the bustub project, and upon that, having an interactive shell. The parser, binder and planner may have very limited functionalities (e.g. don't support subqueries), but will support at least the following queries (as in the executor test):

```
-- select star
SELECT * FROM empty_table2;

-- simple filter
SELECT col_a, col_b FROM test_1 WHERE col_a < 500

-- select with limit
SELECT colA, colB FROM test_3 LIMIT 10

-- insert with values
INSERT INTO empty_table2 VALUES (100, 10), (101, 11), (102, 12)

-- insert with select from
INSERT INTO empty_table2 SELECT col_a, col_b FROM test_1 WHERE col_a < 500

-- update
UPDATE test_3 SET colB = colB + 1;

-- delete
DELETE FROM test_1 WHERE col_a == 50;

-- joins with explicit condition
SELECT test_1.col_a, test_1.col_b, test_2.col1, test_2.col3 FROM test_1 JOIN test_2 ON test_1.col_a = test_2.col1;

-- simple aggregation
SELECT COUNT(col_a), SUM(col_a), min(col_a), max(col_a) from test_1;

-- group aggregation
SELECT count(col_a), col_b, sum(col_c) FROM test_1 Group By col_b HAVING count(col_a) > 100

-- select distinct (w/o support for distinct aggregation like `count(distinct colC)`)
SELECT DISTINCT colC FROM test_7

-- create table
CREATE TABLE table (v1 int);

-- drop table
DROP TABLE table;
```

Currently I have no idea how much code work will it take to have such binder / parser / planner / interactive shell inside bustub. I also don't expect to finish everything before the fall semester. From the discussion inside the Slack channel, cc @garrisonhess may already have some ideas on how to implement a SQLite wrapper (instead of writing our own version of every component) around bustub (But I don't know the progress. Would you please share about what you've done if you have time? Thanks!). Anyway, it would be good if we can use bustub like other database systems (e.g. SQLite) to accept SQL as input.

I'd like to bring this topic to discussion. Comments are welcomed!

- [x] bind agg, expressions https://github.com/cmu-db/bustub/pull/295
- [x] integrate binder with catalog https://github.com/cmu-db/bustub/pull/295
- [x] bind joins https://github.com/cmu-db/bustub/pull/324
- [x] #354
- [x] plan agg and scan https://github.com/cmu-db/bustub/pull/307
- [x] plan group agg https://github.com/cmu-db/bustub/pull/346
- [x] plan join https://github.com/cmu-db/bustub/pull/327
- [x] plan create / drop table https://github.com/cmu-db/bustub/pull/333
- [x] plan insert https://github.com/cmu-db/bustub/pull/338
- [ ] #359
- [x] implement explain https://github.com/cmu-db/bustub/pull/351
- [x] integrate with executor
- [x] #355
- [x] bind and plan order by && limit https://github.com/cmu-db/bustub/pull/351
- [ ] #356
- [ ] #357
- [ ] #358

**Comment by skyzh** [comment]
Missed one important functionality:

```
--- explain
EXPLAIN SELECT DISTINCT colC FROM test_7
```

**Comment by lmwnshn** [comment]
As a nice-to-have (doesn't have to come with this change or be written by you, other TAs might be able to pick it up), being able to visualize the plan tree would be helpful for students too. e.g., a former TA Ricky wrote the code to visualize B-Trees via graphviz and I think that was a major improvement in student quality of life.

**Comment by GavinRay97** [comment]
I can volunteer to implement the expression AST + query plan visualizer.

Also, it's certainly not as ergonomic as SQL, but for fast feedback during development and prototyping, may be useful to mention `cling` to students (C++ repl using `clang`, formed the basis for new `llvm/clang-repl` project):

- https://blog.llvm.org/posts/2020-11-30-interactive-cpp-with-cling/

CLion recently gained support for it in-editor which makes it kind of nice:
- https://www.jetbrains.com/help/clion/cling-integration.html#issues

Can give a comfy feedback loop compared to edit -> compile -> run, more like a scripting language 👍

**Comment by skyzh** [comment]
Task list updated.

**Comment by skyzh** [comment]
All of the tasks are already done in this roadmap (there're still pending PRs). BusTub now has decent Postgres-dialect SQL support. Close this for now.
