### ISSUE TITLE
executor_test.cpp SimpleGroupbyAggregation

### ISSUE THREAD

**Issue by sg20180546** [cmu-db/bustub#260]
hello . I glad you to open this bustub open source educational project to public.
It helps me to understand database internal a lot

during solving the executor_test.cpp,
Test SimpleGroupbyAggregation seems little weird to me.
That is, the test demands `count(col_a), col_b, sum(col_c) FROM test_1 Group By col_b HAVING count(col_a) > 100`
but the output schema init as `agg_schema = MakeOutputSchema({{"countA", count_a}, {"colB", groupby_b}});`

I think that correct output schema shoud initialized as
`agg_schema = MakeOutputSchema({{"countA", count_a}, {"colB", groupby_b}, {"sumC", sum_c} });`

Thanks.

**Comment by skyzh** [comment]
That’s true, I think there’s something wrong with that. I’ll propose a fix later.
