### ISSUE TITLE
Discussion: vendor gtest

### ISSUE THREAD

**Issue by skyzh** [cmu-db/bustub#270]
Currently we will need to clone gtest from GitHub every time we configure CMake. This would introduce some instability when running build scripts in CI. Maybe it would be better for us to vendor everything. Not sure how other projects deal with gtest.

**Comment by lmwnshn** [comment]
If I remember correctly, I brought in this change to mimic what we did for NoisePage. The original reason for not vendoring gtest is CMake and software engineering best practice yadayada.

However, I note that _not_ vendoring gtest is the reason the old autograders got broken (e.g., when they renamed master -> main). Given (1) limited engineering resources, (2) upstream being very ready to make breaking changes, and (3) I don't think we care very much about new versions of gtest anyway, I am in favor of vendoring gtest.

Actually, I wanted to propose switching away from gtest to catch2 for BDD tests anyway. Students would need to learn this, but it reads a lot more naturally for autograders, the sample tests we provide, and test failures. But that's a separate discussion.

**Comment by GavinRay97** [comment]
The way that the `GTest` dependency is configured in CMake is very old, dating before `FetchContent` API

Additionally, the version isn't pinned -- it's set to `master`, so if there are breaking changes, tests would start failing

You can use `FetchContent` with a pinned version or commit hash, and CMake will cache the result -- it's much faster and also cleaner/less code. This is what Google suggests for how to include in CMake build
- https://google.github.io/googletest/quickstart-cmake.html

For my BusTub re-implementation project, I set it up like this:

```cmake

FetchContent_Declare(googletest
        GIT_REPOSITORY https://github.com/google/googletest.git
        GIT_TAG release-1.12.1
        )
FetchContent_MakeAvailable(googletest)

FetchContent_Declare(fmt
        GIT_REPOSITORY https://github.com/fmtlib/fmt.git
        GIT_TAG 9.0.0
        )
FetchContent_MakeAvailable(fmt)

enable_testing()
add_executable(bustub_cpp_reimpl
        main.cpp)
target_link_libraries(bustub_cpp_reimpl
        PRIVATE
        GTest::gtest_main
        fmt::fmt)

include(GoogleTest)
gtest_discover_tests(bustub_cpp_reimpl)
```

Hope this is useful info 👍

**Comment by lmwnshn** [comment]
@GavinRay97 You're right! I was under the impression that we had already been using FetchContent back then. I must've been thinking of NoisePage. Thanks for pointing it out!

Another advantage to vendoring (which is maybe less relevant for BusTub) is that as long as you've cloned the repo, you can work without internet access ("doing homework on the airplane" scenario). FetchContent will fetch at cmake time, and if they've deleted their build folder (which is our usual solution to CLion issues), then they'll need to refetch.

@skyzh Thoughts? I don't have strong opinions either way, I think you can do what you want.

**Comment by skyzh** [comment]
> FetchContent will fetch at cmake time, and if they've deleted their build folder (which is our usual solution to CLion issues), then they'll need to refetch.

This is annoying in my case, especially when I was working on bustub-private at the airport / in the coffee shop. We will always need a fresh build to verify if everything works, where the cmake build directory is deleted during the verification process. So I'd prefer vendoring the source code anyway instead of pinning a commit.

**Comment by GavinRay97** [comment]
> Another advantage to vendoring (which is maybe less relevant for BusTub) is that as long as you've cloned the repo, you can work without internet access

This is a good point
