### ISSUE TITLE
clang-tidy and clang-format finder

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/bustub#28]
Figure out what changed in recent versions of Mac / homebrew; where are the `clang-format` and `clang-tidy` binaries being installed? Works for some people, doesn't work for others. I don't have a recent Mac, so I'm probably going to rely on someone else to fix this.

Temporary workaround: figure out where `clang-tidy` and `clang-format` are, and add them to your PATH.

https://github.com/cmu-db/bustub/blob/master/CMakeLists.txt#L15

**Comment by liu-du** [comment]
Hello,  

Looks like I have to remove the double quotes in the `HINTS` option in `find_program`, only then cmake will find the executable in `/usr/local/opt/llvm@8/bin` (in my case). I'm using a mac and I'm not experienced in cmake/c++, not sure if this will work for windows/linux machines? 

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d451c29..34f5197 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -25,7 +25,7 @@ enable_testing()
 # clang-format
 find_program(CLANG_FORMAT_BIN
         NAMES clang-format clang-format-8
-        HINTS "${BUSTUB_CLANG_SEARCH_PATH}")
+        HINTS ${BUSTUB_CLANG_SEARCH_PATH})
 if ("${CLANG_FORMAT_BIN}" STREQUAL "CLANG_FORMAT_BIN-NOTFOUND")
     message(WARNING "BusTub/main couldn't find clang-format.")
 else()
@@ -35,7 +35,7 @@ endif()
 # clang-tidy
 find_program(CLANG_TIDY_BIN
         NAMES clang-tidy clang-tidy-8
-        HINTS "${BUSTUB_CLANG_SEARCH_PATH}")
+        HINTS ${BUSTUB_CLANG_SEARCH_PATH})
 if ("${CLANG_TIDY_BIN}" STREQUAL "CLANG_TIDY_BIN-NOTFOUND")
     message(WARNING "BusTub/main couldn't find clang-tidy.")
 else()
```

result:
```
build ‹master* M› » cmake ..
-- BusTub/main found clang-format at /usr/local/opt/llvm@8/bin/clang-format
-- BusTub/main found clang-tidy at /usr/local/opt/llvm@8/bin/clang-tidy
```

**Comment by lmwnshn** [comment]
Coming back one year later, you're absolutely correct! In CMake, lists are ;-separated strings. For example `a;string;list;here`.
If you put quotes around a list variable, it gets pasted in as `a;string;list;here`. If you don't, it gets pasted in as `a string list here`

So `HINTS "${BUSTUB_CLANG_SEARCH_PATH}"` expands into `HINTS /usr/local/bin;/usr/bin;/usr/local/opt/llvm/bin;etc`.
But checking the CMake find_program documentation, we want it to expand to `HINTS /usr/local/bin /usr/bin /usr/local/opt/llvm/bin etc`.

If you make a PR, I will merge it. Thanks for reminding me this existed!

**Comment by liu-du** [comment]
thanks for responding, I raised #107 just now.
