### ISSUE TITLE
Proposal: introduce ThreadSanitizer to bustub

### ISSUE THREAD

**Issue by skyzh** [cmu-db/bustub#288]
Currently we've already enabled AddressSanitizer + LeakSanitizer. We can further add a CI step / grading step to run all tests under thread sanitizer, so as to find potential issues with deadlocks in the bustub project.

**Comment by skyzh** [comment]
One useful thing about thread sanitizer is that it can find potential deadlocks and problems with atomic variables. e.g. if there are two mutex used in two threads, where each thread acquires the mutex in different order, thread sanitizer will report a warning.

**Comment by GavinRay97** [comment]
One question -- I could not find how it is that `LeakSanitizer` is currently enabled, is this part of ASAN by default?

Also, if making changes, another to consider might be to swap `-O0` for `-Og` in debug mode:

> If you are not using some other optimization option, consider using -Og (see [Optimize Options](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#Optimize-Options)) with -g.

![image](https://user-images.githubusercontent.com/26604994/187085391-df2452d0-885b-4c4a-a328-487d560ab40b.png)

**Comment by skyzh** [comment]
Yes, it's part of ASAN.
