### ISSUE TITLE
Extendible Hash Index: Gradescope tests are not broad enough

### ISSUE THREAD

**Issue by czarnoj** [cmu-db/bustub#292]
I was refactoring my hash table code and I introduced a severe bug, that ended up passing all the tests on grade scope.
Additionally, I was able to craft some test data that broke my code.

If you guys want to deal with this and need more detail, we should probably do so in private, as I'm afraid I might give away a critical piece of project.

**Comment by skyzh** [comment]
Sure, feel free to email me with the email on my GitHub profile page. btw, we might not use hash table for project 2 this semester, so we might come up with a fix later.

**Comment by skyzh** [comment]
Also if you have code to share with me, you can add me as a collaborator in a GitHub private repo.
