### ISSUE TITLE
Add page_type enum to every Page

### ISSUE THREAD

**Issue by lmwnshn** [cmu-db/bustub#31]
We want a page_type enum in every Page class. Useful for autograding.

https://github.com/cmu-db/bustub/blob/master/src/include/storage/page/page.h#L28

**Comment by skyzh** [comment]
We already have one. Feel free to reopen if I'm wrong with that. https://github.com/cmu-db/bustub/blob/8ec6039d3c7129c8b7e8209b6a7fba2dc2c4dddf/src/storage/page/b_plus_tree_page.cpp#L22
