### ISSUE TITLE
[FR]: Clarify docstrings about `Pin` and `Unpin`, add note about why `Unpin` must be called to make items victimizable

### ISSUE THREAD

**Issue by GavinRay97** [cmu-db/bustub#321]
I've generally found the doc comments in the project very helpful for understanding what things are supposed to do/why.

One major source of confusion for me has been the `Replacer` docs and unit tests. Specifically around the semantics of `Pin`/`Unpin`.

From the Buffer Pool lecture in 2019, the slide says:
- > _"When a page is accessed, the reference bit is set to `1`"_

<details>
  <summary><b>CLICK TO DISPLAY IMAGE</b></summary>

   ![image](https://user-images.githubusercontent.com/26604994/188916937-820e6f77-d274-4004-b710-a584c2826e5b.png)
</details>

This makes sense.

However, the doc comment for `Unpin`, and the unit test, present some confusing/conflicting information:

https://github.com/cmu-db/bustub/blob/f2625afe2ba4cf07c76bae256a409938582c2815/src/include/buffer/replacer.h#L40-L44

https://github.com/cmu-db/bustub/blob/f2625afe2ba4cf07c76bae256a409938582c2815/test/buffer/clock_replacer_test.cpp#L50-L51

The `Unpin` function comment seems to say that the method implies a page is NOT being used any more

But in the tests, the comment says that calling `Unpin` should set `reference_bit` to `1`, as though the page is being accessed
Maybe the docs in both of these places can be modified to make it more clear?

On [this page](https://sort.veritas.com/public/documents/vie/7.1/linux/productguides/html/infoscale_smartio_solutions_71_lin/ch02s06s04.htm), the following definitions of `Pin`/`Unpin` are given which I thought was decent:

> "The **pin** operation prevents the data from being evicted from the cache. You can pin commonly used database objects so that SmartIO does not evict the data and later need to cache the data again. The pinned data is kept in the cache indefinitely, until it is deleted or explicitly unpinned."

> "The **unpin** operation removes data from the pinned state. The unpin operation does not cause the data to be immediately evicted. SmartIO considers the data for eviction in the same way as any other data, when space is required in the cache."

Though with these descriptions, one last source of confusion exists at why pages need to be `Unpin`'ed to become available:

https://github.com/cmu-db/bustub/blob/f2625afe2ba4cf07c76bae256a409938582c2815/test/buffer/clock_replacer_test.cpp#L25-L33

None of these frames were in a `Pin`'ed state, why do we need to `Unpin` them first?

**Comment by skyzh** [comment]
We’ve changed this yesterday. PTAL at our new API.

**Comment by skyzh** [comment]
It’s here -> https://github.com/cmu-db/bustub/blob/master/src/include/buffer/lru_k_replacer.h

**Comment by GavinRay97** [comment]
My heroes 😅

**Comment by GavinRay97** [comment]
Wow this one is so much easier to understand, thanks a lot.
Particularly the API rename, like `RecordAccess`, `SetEvictable`

I think students will have much easier time 👍
