### ISSUE TITLE
timestamp_type.cpp should use `snprintf`, not `sprintf`

### ISSUE THREAD

**Issue by peterb12** [cmu-db/bustub#322]
`sprintf` is deprecated on recent MacOS SDKs. The `// NOLINT` directives won't prevent a compilation warning (and thus an error). Since the since of the buffers being written to is known, these uses should be changed to `snprintf` instead, which is safer.

**Comment by skyzh** [comment]
Good catch! Will fix soon.

**Comment by skyzh** [comment]
This is not related to a course project, so it would be fine to send a PR! Thanks!

**Comment by peterb12** [comment]
Posted here: https://github.com/cmu-db/bustub/pull/326
