### ISSUE TITLE
using page_slot = frame_id_t in BufferPoolManager page table and free list could make it clearer

### ISSUE THREAD

**Issue by sitano** [cmu-db/bustub#33]
It's unclear how frame_id_t space of values relates to the BufferPoolManager.

Using the term `using page_slot = frame_id_t` could simplify the understanding of what is happening with the free pages list and the pool itself.

Having `page_slot = frame_id_t` allows not having separate mapping.

**Comment by skyzh** [comment]
I think the lectures are already very clear with what's frame and what's page. I don't think it's a good idea, but it's open to discussion. You can move this thread to GitHub Discussion.
