### ISSUE TITLE
What happens to https://15445.courses.cs.cmu.edu/fall2022.

### ISSUE THREAD

**Issue by brandb97** [cmu-db/bustub#443]
I can't open https://15445.courses.cs.cmu.edu/fall2022 in my firefox browser. Are their servers down or it's just my problem.

**Comment by lmwnshn** [comment]
cs.cmu.edu domain has been having issues over the past week (it's currently break). Not on our end, I think. Try again in a few days? They will probably notice and fix sometime next week.

**Comment by brandb97** [comment]
Thx!


I am doing you course's project right now. And they are awesome, both the course and the project. But I am not from your school and I feel really frustrate to find your course's resourse is missing.
So would you please tell me where can I find the resourse, especially the ppts, is they still available now.


By the way, I am a Chinese student, please forgive me about my creepy English.


------------------

LEAP&nbsp;OF&nbsp;FAITH
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Wan Shen ***@***.***&gt;;
Send time:&nbsp;Saturday, Oct 22, 2022 8:15 PM
***@***.***&gt;; 
Cc:&nbsp;"LEAP OF ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [cmu-db/bustub] What happens to https://15445.courses.cs.cmu.edu/fall2022. (Issue #443)





 
Closed #443 as completed.

**Comment by lmwnshn** [comment]
I think Andy has fixed the website and it should be back up now.
