### ISSUE TITLE
How to make sure the page id returned by redo newpage is the same as the one in log record?

### ISSUE THREAD

**Issue by xinzhu-cai** [cmu-db/bustub#48]
Currently, for redo newpage, we use the page id in the log record. When we create new pages in recovery, the returned page ids should be the same as the original pages since the disk manager just uses an increasing counter for the page id. The counter starts over when the database is deleted and you're creating new pages is the same order as they were originally created, so the page ids should be the same.

However, what if we want to pass a page id as a parameter to newpage? Seems like we need to add an input parameter to NewPageImpl in buffer_pool_manager. Inside this function, we also need to check whether the requested page id has already been allocated.

**Comment by lmwnshn** [comment]
I think this was resolved.
