### ISSUE TITLE
anybody can share me with the project solution? for self study

### ISSUE THREAD

**Issue by astronaut0131** [cmu-db/bustub#50]
just as a reference for self study, not for evil :)

**Comment by apavlo** [comment]
Which project? We are going to release the solution for Project #2.

**Comment by astronaut0131** [comment]
@apavlo       
all of them, I want to take a look at the sophisticated implementation after I finish each project, so where can I find the solution release?

**Comment by apavlo** [comment]
We're working on it with @xinzhu-cai

**Comment by astronaut0131** [comment]
thanks, looking forward to it :)

**Comment by apavlo** [comment]
Other schools are using BusTub for their projects because of the COVID-19 outbreak. Try GradeScope using access code 9ZJPVE

**Comment by ziyi-yan** [comment]
> Other schools are using BusTub for their projects because of the COVID-19 outbreak. Try GradeScope using access code 9ZJPVE

Hi, @apavlo! It seems that this access code is disabled now. How can non-CMU students access GradeScope for 2020 fall? Or, we still have a one for 2019 fall?

**Comment by bencwallace** [comment]
> Which project? We are going to release the solution for Project #2.

Did the solution ever get released?
