### ISSUE TITLE
log: PastLastSlash returns incorrect results

### ISSUE THREAD

**Issue by Sanzo00** [cmu-db/bustub#507]
https://github.com/cmu-db/bustub/blob/49deaa136c2b0d2d0f4eb417cf5f4766c181c4da/src/include/common/logger.h#L44-L46

When I run `PastLastSlash("/home/xxx/test.txt")`, the result returned is `home/xxx/test.txt`, but I I think `test.txt` is correct.

I checked this blog (https://blog.galowicz.de/2016/02/20/short_file_macro/), I think it should be changed to:

```cpp
static constexpr auto PastLastSlash(cstr a, cstr b) -> cstr {
  return *a == '\0' ? b : *a == '/' ? PastLastSlash(a + 1, a + 1) : PastLastSlash(a + 1, b);
}
```

**Comment by skyzh** [comment]
feel free to submit a PR to fix that!

**Comment by Sanzo00** [comment]
I created a PR in (#509), please review my submission.
