### ISSUE TITLE
When can the full test cases be publicly available?

### ISSUE THREAD

**Issue by RileyWen** [cmu-db/bustub#51]
Just want to judge the correctness of the project implementations more comprehensively.🙂

**Comment by cakebytheoceanLuo** [comment]
Do they have more tests?

**Comment by apavlo** [comment]
Try GradeScope using access code 9ZJPVE

**Comment by NWdawg** [comment]
> Try GradeScope using access code 9ZJPVE

Hi Prof. Andy. I've done SimpleDB in Java and now trying to switch gear to C++ and reviewing DBMS with your 15-445. 

The grade scope is only accepting project 1 and 2 rn(and seems like they are closing in 2 months), other HWs and projects submissions are closed. Is it by purpose or it's just malfunctioning? 

Any chance you can open up all the submissions permanently?

**Comment by jaedongtang** [comment]
Hi Prof. Andy,

The submissions for project 3 and 4 are closed on the gradescope now. Could you reopen them in the future?
