### ISSUE TITLE
Duplicate file open mode (bit *or* operation)

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [cmu-db/bustub#55]
https://github.com/cmu-db/bustub/blob/0bb0669659e71ac98011c6c266d33a2aa9e5697d/src/storage/disk/disk_manager.cpp#L51

I suppose there should be `db_io_.open(db_file, std::ios::binary | std::ios::in | std::ios::out);`, to open a file, if it exists.

`std::ios::out | std::ios::out` is not bug (and would be optimized by the compiler), but not readable. :smile_cat:

**Comment by apavlo** [comment]
Can you send a PR?
