### ISSUE TITLE
Project 2 cannot pass gradescope test due to internal header problems.

### ISSUE THREAD

**Issue by RileyWen** [cmu-db/bustub#58]
```
test/include/logging/common.h:36:16: error: the const qualified variable 'col' is copy-constructed from a const reference; consider making it a const reference [performance-unnecessary-copy-initialization,-warnings-as-errors]
    const auto col = schema->GetColumn(i);
               ^
              &
```

When I was trying to grade Project 2 on gradescope, I found that check-lint cannot succeed due to the error above. There is a historical commit on bustub which fixed this problem. So it seems the code on gradescope is the earliest version. Can you please update the internal code on gradescope? Thanks!

**Comment by RileyWen** [comment]
There is another problem on Project 2 grader script: When the grader starts building, it tries to copy a non-source file into the source directory.
```
cp: cannot stat '/autograder/submission/build_support/libp1_static.a': No such file or directory
```

**Comment by cakebytheoceanLuo** [comment]
This issue confirtmed.
- `test/include/logging/common.h` should be test intern used, since the file in my project is correct with the link-check.
- `build_support/libp1_static.a'` is lacked also in our git repo (and in all previous commits).

**Comment by Jack-Clark** [comment]
> ```
> test/include/logging/common.h:36:16: error: the const qualified variable 'col' is copy-constructed from a const reference; consider making it a const reference [performance-unnecessary-copy-initialization,-warnings-as-errors]
>     const auto col = schema->GetColumn(i);
>                ^
>               &
> ```
> 
> When I was trying to grade Project 2 on gradescope, I found that check-lint cannot succeed due to the error above. There is a historical commit on bustub which fixed this problem. So it seems the code on gradescope is the earliest version. Can you please update the internal code on gradescope? Thanks!

I'm having the same issue. It would be great to have this fixed.

**Comment by greenmoon55** [comment]
I haven't tried Project 2, but maybe you could try rebasing to `5d2a9d5`
See https://github.com/cmu-db/bustub/issues/52#issuecomment-609502337

**Comment by RileyWen** [comment]
> I haven't submitted Project 2, but maybe you could try rebasing to `5d2a9d5`
> See [#52 (comment)](https://github.com/cmu-db/bustub/issues/52#issuecomment-609502337)

No. Any commit earlier than `f3669c3e Update Projects According to Piazza Discussions (#49)` won't even compile. Quite weird. It seems that the 'src' part of the grader code keeps the lastest version but the `test/include/logging/common.h` stays at the earliest commit?

**Comment by RajaSimha** [comment]
> ```
> test/include/logging/common.h:36:16: error: the const qualified variable 'col' is copy-constructed from a const reference; consider making it a const reference [performance-unnecessary-copy-initialization,-warnings-as-errors]
>     const auto col = schema->GetColumn(i);
>                ^
>               &
> ```
> 

Could it be possible to fix this soon or suggest an alternative (something like a patch) to bypass the error and run tests on gradescope please? Thanks in advance!

**Comment by garrisonhess** [comment]
Closing since this project is deprecated.
