### ISSUE TITLE
Test: is the bpm_bench.cpp same on both autograder and bustub repo?

### ISSUE THREAD

**Issue by sprayerH** [cmu-db/bustub#583]
in spring2023 version, I found that the bpm bench test was OK on my pc but always coredump on autograder quickly.   
![image](https://github.com/cmu-db/bustub/assets/39316418/312885f4-a9be-4890-abbc-02d1d42a419a)

**Comment by sprayerH** [comment]
OS: ubuntu 20.04
cxx compiler: clang-12 (sometimes clang-17)
There are some problem on my linux, so i dont use clang-14

**Comment by skyzh** [comment]
It's the same. This repo is not intended for autograder issue. Please go to unofficial discord channel for help.
