### ISSUE TITLE
Gradescope for Non CMU student

### ISSUE THREAD

**Issue by adriangomez24** [cmu-db/bustub#591]
After looking at issue #210 , I followed the steps as follows but it still says that course entry code is invalid. Has gradescope for non-cmu students been turned off? 

<img width="544" alt="Screen Shot 2023-08-10 at 11 37 04 PM" src="https://github.com/cmu-db/bustub/assets/109683617/3bd92f1c-ac7a-49ff-98ba-6e451a8a93ee">

**Comment by adriangomez24** [comment]
I got the course code from here https://15445.courses.cs.cmu.edu/fall2022/project0/

**Comment by skyzh** [comment]
we track grader issues in this repo, consider using Discord server for help :)
