### ISSUE TITLE
Aggregation Executor - How to get correct ordering of columns in output tuple

### ISSUE THREAD

**Issue by Jack-Clark** [cmu-db/bustub#60]
In Project 3 Task 2, for the aggregation executor, I can't see how to ensure the Next() method obeys the OutputSchema column ordering. I have an AggregateKey and an AggregateValue, but I don't see how I can know in which order I should combine their contents to create the correct output tuple, given that they are both essentially vector<Value> types and as far as I can see the Value type gives no information about which column it corresponds to. I feel like I'm missing something obvious.

As an example, in ExecutorTest - SimpleGroupByAggregation, the provided output schema has 3 columns: countA, colB, sumC where colB is a group by column. I can see how we can create a tuple that has all of the group by columns to the left, and all aggregates to the right:
```
AggregateKey key = aht_iterator_.Key();
AggregateValue vals = aht_iterator_.Val();
const size_t num_cols = key.group_bys_.size() + vals.aggregates_.size();
assert(num_cols == plan_->OutputSchema()->GetColumnCount());
std::vector<Value> combined_cols;
combined_cols.reserve(key.group_bys_.size() + vals.aggregates_.size());
combined_cols.insert(combined_cols.end(), key.group_bys_.begin(), key.group_bys_.end());
combined_cols.insert(combined_cols.end(), vals.aggregates_.begin(), vals.aggregates_.end());
*tuple = Tuple(combined_cols, plan_->OutputSchema());
```  
I understand that the output schema specifies the ordering we want, but I don't see how it is possible to know which values in the AggregateKey and AggregateValue correspond to which columns in the output schema, and therefore how to combine them to obey the output schema.

Any help would be greatly appreciated. Thanks in advance.

**Comment by lmwnshn** [comment]
Check out AggregateValueExpression and/or Column.
