### ISSUE TITLE
Unsupported Distribution Error Message

### ISSUE THREAD

**Issue by Tiberius202** [cmu-db/bustub#606]
Hello, I am running Linux Mint 21.2 which should be based off of Ubuntu 22.04 which is explicitly supported. 

For now I will skip the check in the shell code

I received the following error message:

++ uname
++ tr '[:lower:]' '[:upper:]'
+ UNAME=LINUX
+ case $UNAME in
++ cat /etc/os-release
++ grep VERSION_ID
++ cut -d '"' -f 2
+ version=21.2
+ case $version in
+ give_up
+ set +x
Unsupported distribution 'LINUX'
Please contact our support team for additional help.
Be sure to include the contents of this message.
Platform: Linux the-anvil 5.15.0-82-generic #91-Ubuntu SMP Mon Aug 14 14:14:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by publicmatt** [comment]
Bump. Doesn't work with Debian 11 either. Ended up running commands manually for linux:
```
  # Update apt-get.
  apt-get -y update
  # Install packages.
  apt-get -y install \
      build-essential \
      clang-14 \
      clang-format-14 \
      clang-tidy-14 \
      cmake \
      doxygen \
      git \
      pkg-config \
      zlib1g-dev \
      libelf-dev \
      libdwarf-dev

```

**Comment by publicmatt** [comment]
And I also ran into an issue with `clang-14` not being in the Debian distribution, so I ran this instead to install it manually:

```
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh 14
```
After which, the previous commands completed with no errors.

**Comment by skyzh** [comment]
unfortunately, you have to install all packages manually :)
