### ISSUE TITLE
Can we have this project in Java please at some point?

### ISSUE THREAD

**Issue by kant777** [cmu-db/bustub#61]
Can we have this project in Java please at some point?

**Comment by apavlo** [comment]
Why?

**Comment by kant777** [comment]
Don't know c++. Lot of the time goes into just figuring what particular line of c++ does instead of learning about how a DB is implemented. so a steep learning curve for someone like me.

**Comment by apavlo** [comment]
Are you proposing that we discard the C++ version that we have been working on for several years and rewrite everything in Java? Who is going to write the Java version?

**Comment by kant777** [comment]
No and I don't know if having another version in Java is a possibility. who is going to write? I am not sure. Ideally, it would be great if the interfaces of bustub can be defined in a language neutral tool and have the code generated in various languages(I don't know of any tool like that exist today. I looked for it but I couldn't find it).

**Comment by apavlo** [comment]
Search for "java simpledb"
