### ISSUE TITLE
bug: incorrect return type for ExtendibleHTableHeaderPage::GetDirectoryPageId

### ISSUE THREAD

**Issue by kenleung5e28** [cmu-db/bustub#625]
The signature for `ExtendibleHTableHeaderPage::GetDirectoryPageId` is:
```cpp
auto GetDirectoryPageId(uint32_t directory_idx) const -> uint32_t;
```
Judging from the intent for this method, its return type should be `page_id_t` instead.

**Comment by lidianzhong** [comment]
I think so, `page_id_t` type should be returned
