### ISSUE TITLE
Why does HashTableBlockPage::Insert need to be thread-safe?

### ISSUE THREAD

**Issue by greenmoon55** [cmu-db/bustub#65]
https://github.com/cmu-db/bustub/blob/7704f90cb1d9f9cc32f648c68b9fa84952bf1796/src/include/storage/page/hash_table_block_page.h#L60
The comment suggests we use CAS here to make insert thread safe. However, from task #4 description, `You will need to have latches on each block so that when one thread is writing to a block other threads are not reading or modifying that index as well.` I'm wondering why we still need CAS when latches ensure only one thread is modifying the block page? 

Actually, if we use CAS to make sure `HashTableBlockPage::Insert` and `HashTableBlockPage ::Remove` are thread-safe, I think we don't need page latches. The table latch is enough. Am I missing something here?

Last but not least, it would be really helpful if https://github.com/cmu-db/bustub/issues/58 can be fixed. 😄  Looks like tests and `/src` are out of sync so the grading script wouldn't work. Now I run multiple threads to insert(resize) and delete concurrently for testing.

**Comment by duynl58** [comment]
Agree.

IMHO, `HashTableBlockPage ::Remove` should be asked to implement CAS as well, and its type should be `bool` instead of `void`.

**Comment by myccccccc** [comment]
https://github.com/cmu-db/bustub/blob/d04bbe9598ff2dd8aba27d36793ef7e254f95696/src/include/container/hash/linear_probe_hash_table.h#L95-L96

I think it is because Insert, Remove and Read they all have to use the read latch, the write latch is only for resizing.

**Comment by ashishnegi** [comment]
@myccccccc OP is talking about Page level read and write latch in `Page.h/cpp` to access the block page.
@greenmoon55 I think we could use CAS if we are doing slot level latching but i think then CAS only would not work - as concurrent add and remove can cause inconsistent state. So, yeah i also want to know why we need CAS in block page.

**Comment by garrisonhess** [comment]
The question is correct in suggesting the CAS was unnecessary.  This is reflected in the extendible hash table project.  Closing since the linear probe hash index is deprecated.  Thanks for the good question and discussion!
