### ISSUE TITLE
executor_factory.cpp CreateExecutor function creat child executor but don't call init() for child 

### ISSUE THREAD

**Issue by habaohaba** [cmu-db/bustub#652]
executor_factory.cpp CreateExecutor function created child executor but don't init() executor for child, so what is the meaning for init() if it is not always be called when executor be constructed.
![屏幕截图 2023-11-07 140847](https://github.com/cmu-db/bustub/assets/34515931/632eda2b-c351-4adc-b489-211f9b00527c)

**Comment by skyzh** [comment]
please use the unofficial Discord server for questions, thanks :)
