### ISSUE TITLE
proposal: update prompt message of `build_support/packages.sh`

### ISSUE THREAD

**Issue by mooxiu** [cmu-db/bustub#672]
When preparing building the project and execute `build_support/packages.sh`, the [prompt message](https://github.com/cmu-db/bustub/blob/63275705bbcc3a075415ed3bf54932f9b1c26b28/build_support/packages.sh#L24) will be:
`Proceed? [Y/n] : ` 

The default behavior (when pressing enter/return without inputting y or n) is do nothing, however, the common practice is that the default behavior should be the same with the capitalized option (in this case, `Y`). If someone assume default behavior to be yes, then it might lead to lack of necessary packages, which is really confusing.

My proposal, change [this line](https://github.com/cmu-db/bustub/blob/master/build_support/packages.sh#L24) from:
```sh
        read -p "Proceed? [Y/n] : " yn
```
to:
```sh
        read -p "Proceed? [y/N] : " yn
```

**Comment by skyzh** [comment]
feel free to submit a pull request
