### ISSUE TITLE
Cmake Error at GoogleTestAddTests.cmake

### ISSUE THREAD

**Issue by li5ch** [cmu-db/bustub#676]
CMake Error at /Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/GoogleTestAddTests.cmake:112 (message):
  Error running test executable.

    Path: '/cmake-build-debug/test/trie_test'
    Result: Segmentation fault
    Output:
      

Call Stack (most recent call first):
  /Applications/CLion.app/Contents/bin/cmake/mac/x64/share/cmake-3.27/Modules/GoogleTestAddTests.cmake:225 (gtest_discover_tests_impl)

**Comment by skyzh** [comment]
Not reproducible

**Comment by ColdRain-Moro** [comment]
I also reproduced this issue when trying to compile `lru_k_replacer_test` in an x86 Docker container running macOS on Apple Silicon chips.
```
[ 98%] Building CXX object test/CMakeFiles/lru_k_replacer_test.dir/buffer/lru_k_replacer_test.cpp.o
[ 98%] Building CXX object test/CMakeFiles/lru_k_replacer_test.dir/__/tools/backtrace.cpp.o
[100%] Linking CXX executable lru_k_replacer_test
CMake Error at /usr/share/cmake-3.22/Modules/GoogleTestAddTests.cmake:83 (message):
  Error running test executable.

    Path: '/home/bustub/bustub/build/test/lru_k_replacer_test'
    Result: Subprocess killed
    Output:
      

Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/GoogleTestAddTests.cmake:179 (gtest_discover_tests_impl)
```

**Comment by aneessh18** [comment]
@H1yame  were you able to resolve the issue ? 
I am facing the same error.
