### ISSUE TITLE
Confusion on loading hash table back from disk after restarting the DBMS in project 2

### ISSUE THREAD

**Issue by kiiirzzz** [cmu-db/bustub#69]
In the handout for project 2 task 1, it says 

> If you create a hash table, write its pages to disk, and then restart the DBMS, you should be able to load back the hash table from disk after restarting.

As far as I am concerned, the implementation should be something like this:

1. Before the DBMS shuts down, the hash table header page id should be stored somewhere on the disk as "metadata" for a table.
2. After restarting the DBMS, the system creates a hash table, passes the old header page id to the hash table instance and then gets all hash indices restored.

It seems that the LinearProbeHashTable class currently being given cannot get "header page id" to restore hash table. Is it my responsibility to implement this?

And the further problem is how to implement the storing and restoring old hash table header page id.

**Comment by jysui123** [comment]
Not sure how to do it in detail, but I remember in the lecture Andy mentioned typically we can rebuild the index (no matter it is b+tree or hash table index) from the data in disk

**Comment by ashishnegi** [comment]
@kiiirzzz I think we can reserve first page (page 0) as the header_page always.
Other way would be to reserve first byte of each page as info about type of page it is : header or block and then scan the complete file to find the header page. This will still need to handle cases where header page moves around and we don't want to pick some other old header page as current header page. So, i think reserving first page to be header_page is easiest.

**Comment by ashishnegi** [comment]
Thinking about more.. now i think it is not possible to reserve page 0 as header_page as their can be multiple hash_table_indexes.
Probably, we store another metadata table which store this info. But yes, LinearHashTable would have another constructor in case we want to build hash_table from existing disk file.

**Comment by apavlo** [comment]
This is not really the place to discuss projects. This is meant for bugs in the code. Please see this FAQ:

https://15445.courses.cs.cmu.edu/fall2020/faq.html#q6
