### ISSUE TITLE
Incorrect comment description for SimpleHashJoinTest

### ISSUE THREAD

**Issue by iamkroot** [cmu-db/bustub#72]
The SQL query describing the test for SimpleHashJoin Executor is from the [previous test](https://github.com/cmu-db/bustub/blob/f581f10982706f9217957884f97b564d2287f951/test/execution/executor_test.cpp#L201). Not a huge bug, but confused me for a bit.

https://github.com/cmu-db/bustub/blob/f581f10982706f9217957884f97b564d2287f951/test/execution/executor_test.cpp#L257-L258

**Comment by garrisonhess** [comment]
Closing since this comment is no longer present.
