### ISSUE TITLE
Bustub Shell crashing when queried for large tables or performing external merge sort

### ISSUE THREAD

**Issue by maxjkwang** [cmu-db/bustub#774]
When querying the bustub web shell for a large table (for example, ` __mock_external_merge_sort_input`), it will abort due to OOM and fail to take any further input (it just shows ... and more internal error messages when you hit enter)
```
bustub> select * from __mock_external_merge_sort_input;
[USER]: Aborted(OOM). Build with -sASSERTIONS for more info.
RuntimeError: Aborted(OOM). Build with -sASSERTIONS for more info.
    at abort (https://15445.courses.cs.cmu.edu/fall2024/bustub/bustub-wasm-shell.js:1:4729)
    at abortOnCannotGrowMemory (https://15445.courses.cs.cmu.edu/fall2024/bustub/bustub-wasm-shell.js:1:59574)
    at _emscripten_resize_heap (https://15445.courses.cs.cmu.edu/fall2024/bustub/bustub-wasm-shell.js:1:59677)
    at https://15445.courses.cs.cmu.edu/fall2024/bustub/bustub-wasm-shell.wasm:wasm-function[385]:0xe10e
    at https://15445.courses.cs.cmu.edu/fall2024/bustub/bustub-wasm-shell.wasm:wasm-function[148]:0x5c09
    at https://15445.courses.cs.cmu.edu/fall2024/bustub/bustub-wasm-shell.wasm:wasm-function[86]:0x2d76
    at https://15445.courses.cs.cmu.edu/fall2024/bustub/bustub-wasm-shell.wasm:wasm-function[667]:0x1d29f
    at https://15445.courses.cs.cmu.edu/fall2024/bustub/bustub-wasm-shell.wasm:wasm-function[331]:0xc06b
    at https://15445.courses.cs.cmu.edu/fall2024/bustub/bustub-wasm-shell.wasm:wasm-function[419]:0xf3b2
    at https://15445.courses.cs.cmu.edu/fall2024/bustub/bustub-wasm-shell.wasm:wasm-function[1819]:0x87b1e
```
While it's definitely not intended to read and output 100000 rows in a table, there might be a better way than just to abort? I see that if we query the table with limit ~65000 it shows 'Table truncated due to output limit.' correctly, so perhaps there could be a similar solution?
Additionally, when queried for the same command in the testcases (`select * from __mock_external_merge_sort_input order by v2 desc, v3 asc limit 100;`), it also aborts due to OOM. Is it due to the web shell not having an actual bpm and disk manager, hence running everything in memory that causes the failure?

**Comment by xx01cyx** [comment]
Hi. Thanks for reporting the issue! We've fixed the problem and the query should run and produce a result now.

Note: We fixed the issue by updating the memory limit of web shell, but it's still possible for it to go OOM. This is because the web shell uses the browser memory as its "disk", so anything written to the disk is actually still in-memory. The disk manager will be improved in the future to alleviate the problem.
