### ISSUE TITLE
Non-cmu's gradescope is not synchronized with the latest code

### ISSUE THREAD

**Issue by sancppp** [cmu-db/bustub#783]
Description
Thanks CMU for providing such a high-quality database course. However, I encountered a compilation failure when submitting my Fall 2024 Project1 code to Gradescope (https://www.gradescope.com/courses/817458).

error info:
```
In file included from /autograder/source/bustub/src/optimizer/eliminate_true_filter.cpp:2:
In file included from /autograder/source/bustub/src/include/execution/plans/filter_plan.h:19:
In file included from /autograder/source/bustub/src/include/catalog/catalog.h:22:
In file included from /autograder/source/bustub/src/include/buffer/buffer_pool_manager.h:25:
/autograder/source/bustub/src/include/storage/disk/disk_scheduler.h:103:59: error: no member named 'DeletePage' in 'bustub::DiskManager'
  void DeallocatePage(page_id_t page_id) { disk_manager_->DeletePage(page_id); }
                                           ~~~~~~~~~~~~~  ^
```
It seems that the provided code on Gradescope is not synced with the latest commits on the master branch of this repository. This issue started from commit [719e73564f85aa6b9afa9fdc6c3e0f4d755db1bd](https://github.com/cmu-db/bustub/commit/719e73564f85aa6b9afa9fdc6c3e0f4d755db1bd) and has not been resolved yet.

Additionally, there are similar reports in an unofficial Discord channel, as shown here: [Discord Message](https://discord.com/channels/724929902075445281/1287999462622498847/1300869631090757734).

Would it be possible for the official team to sync the code regularly or implement an automated sync using GitHub Actions?

Thank you for your assistance!

**Comment by apavlo** [comment]
@sancppp Can you try it now? I couldn't find your submission based on your Github `@qq.com` email.

**Comment by sancppp** [comment]
> @sancppp Can you try it now? I couldn't find your submission based on your Github `@qq.com` email.

I have just made a submission using the account [sancpp@qq.com](mailto:sancpp@qq.com). Please check it. It seems that the issue is caused by the changes introduced in [this commit](https://github.com/cmu-db/bustub/commit/719e73564f85aa6b9afa9fdc6c3e0f4d755db1bd#diff-200a7162a17bbdd7f38cf457aafc679778bceb937e41fe1e3ce31a5bfdeb2592R103), which added additional methods to `DiskManager`.

**Comment by sancppp** [comment]
It seems resolved. Thank you for your time.
