### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [cmu-db/bustub#82]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [BufferPoolManager](https://github.com/cmu-db/bustub/blob/5eaa41138152ee1fffb0b09cf0b0aa99baff3bed/src/buffer/buffer_pool_manager.cpp#L20)
- [BustubInstance](https://github.com/cmu-db/bustub/blob/caf086904238a0dfda6c4b3cd808e6a1bb2d3f21/src/include/common/bustub_instance.h#L26)

**Comment by garrisonhess** [comment]
Not at this time.  There are various potential safety and modernization refactors.  Please feel free to submit a PR for any improvements.
