### ISSUE TITLE
LRU Testing : lru_replacer_test.cpp

### ISSUE THREAD

**Issue by prateek-agarwal-git** [cmu-db/bustub#96]
Line 26, 32, and 38: 1 is unpinned 2 times. Due to the last unpin, 1 becomes the most recently used block and hence should not be evicted in line 38.

**Comment by mrdongmen** [comment]
https://github.com/cmu-db/bustub/blob/0c92f70e36fa7a0f2718dd0e772b42ffb1a0e57c/test/buffer/buffer_pool_manager_test.cpp#L26-38

**Comment by skyzh** [comment]
This project has been deprecated.
